### ISSUE TITLE
[Feature Request] Grenz - Show the moderator who actioned

### ISSUE THREAD

**Issue by james-jimjam** [PaddoInWonderland/ValeOfMushrooms#9]
If a message has been deleted, it shows the original sender of the message and the message content along with the channel however it does not show the user (usually a moderator) who deleted the message. Would it be possible to log the person who deleted the message too?

This would help a lot with server moderation especially when coaching a new team of moderators as it is important to make sure everyone (including the mods) are doing the correct thing.

Let me know if you need assistance with this in terms of testing or clarification.

**Comment by SatanKT** [comment]
I'd also love to see this feature

**Comment by PaddoInWonderland** [comment]
Showing _who_ removed a message means looking for it in the audit logs. Technically it is possible to get the author of the action. However, since the audit logs (in discord.py) do not provide a context it's going to be unreliable to match an audit log action with an actual event logged by GPv3. In fact, it was once part of GPv3 as a main feature until someone noticed the unreliable retrieval of the audit log action.

**Comment by PaddoInWonderland** [comment]
Closed due to inactivity.
